---
# Source: harbor/templates/registry/registry-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: "myharbor2-registry"
  labels:
    heritage: Helm
    release: myharbor2
    chart: harbor
    app: "harbor"
spec:
  ports:
    - name: http-registry
      port: 5000

    - name: http-controller
      port: 8080
  selector:
    release: myharbor2
    app: "harbor"
    component: registry
