---
# Source: harbor/templates/registry/registry-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "myharbor2-registry"
  labels:
    heritage: Helm
    release: myharbor2
    chart: harbor
    app: "harbor"
type: Opaque
data:
  REGISTRY_HTTP_SECRET: "MjV0eDltYnpQVzFiVlJHOA=="
  REGISTRY_REDIS_PASSWORD: ""
---
# Source: harbor/templates/registry/registry-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "myharbor2-registry-htpasswd"
  labels:
    heritage: Helm
    release: myharbor2
    chart: harbor
    app: "harbor"
type: Opaque
data:
  REGISTRY_HTPASSWD: "aGFyYm9yX3JlZ2lzdHJ5X3VzZXI6JDJhJDEwJE8yNW1zYXNaMFo2am1hZ2hRQnRmWnVxblJEUnBsOEVpRnZhV2pWeHgud1MwRlkubkdJSlJD"
