---
# Source: harbor/templates/core/core-dpl.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myharbor1-core
  labels:
    heritage: Helm
    release: myharbor1
    chart: harbor
    app: "harbor"
    component: core
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      release: myharbor1
      app: "harbor"
      component: core
  template:
    metadata:
      labels:
        release: myharbor1
        app: "harbor"
        component: core
      annotations:
        checksum/configmap: da7d57dd98c9e791dc0bd44b289f55ceb08c4e5677f161022bfce1d410bff42d
        checksum/secret: cf98cd638f794d03c7e1ee918f7a59b4246d673353930dc5a292a3ef2840bdad
        checksum/secret-jobservice: 7a2735c52cb69d109d203ea913d267fec9ee6889b6014ef423dc09b7d474f751
    spec:
      securityContext:
        runAsUser: 10000
        fsGroup: 10000
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 120
      containers:
      - name: core
        image: goharbor/harbor-core:v2.9.1
        imagePullPolicy: IfNotPresent
        startupProbe:
          httpGet:
            path: /api/v2.0/ping
            scheme: HTTP
            port: 8080
          failureThreshold: 360
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/v2.0/ping
            scheme: HTTP
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v2.0/ping
            scheme: HTTP
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: "myharbor1-core"
        - secretRef:
            name: "myharbor1-core"
        env:
          - name: CORE_SECRET
            valueFrom:
              secretKeyRef:
                name: myharbor1-core
                key: secret
          - name: JOBSERVICE_SECRET
            valueFrom:
              secretKeyRef:
                name: "myharbor1-jobservice"
                key: JOBSERVICE_SECRET
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/core/app.conf
          subPath: app.conf
        - name: secret-key
          mountPath: /etc/core/key
          subPath: key
        - name: token-service-private-key
          mountPath: /etc/core/private_key.pem
          subPath: tls.key
        - name: ca-download
          mountPath: /etc/core/ca
        - name: psc
          mountPath: /etc/core/token
      volumes:
      - name: config
        configMap:
          name: myharbor1-core
          items:
            - key: app.conf
              path: app.conf
      - name: secret-key
        secret:
          secretName: myharbor1-core
          items:
            - key: secretKey
              path: key
      - name: token-service-private-key
        secret:
          secretName: myharbor1-core
      - name: ca-download
        secret:
      - name: psc
        emptyDir: {}
