---
# Source: harbor/templates/core/core-dpl.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myharbor2-core
  labels:
    heritage: Helm
    release: myharbor2
    chart: harbor
    app: "harbor"
    component: core
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      release: myharbor2
      app: "harbor"
      component: core
  template:
    metadata:
      labels:
        release: myharbor2
        app: "harbor"
        component: core
      annotations:
        checksum/configmap: 9c1f5e98499eb05ad06749bd53bc6beee721e4a5032286d7f3674b7e40908a28
        checksum/secret: bd350a7c84408265f0b50e14d8296dbab5f2cbe03bb0231a4f7b2bb39550f7e6
        checksum/secret-jobservice: 304394fb1d49d18ee1429079b2af313c0e6aeadd70ab8f23b05e817ec0c73ee9
    spec:
      securityContext:
        runAsUser: 10000
        fsGroup: 10000
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 120
      containers:
      - name: core
        image: goharbor/harbor-core:v2.9.1
        imagePullPolicy: IfNotPresent
        startupProbe:
          httpGet:
            path: /api/v2.0/ping
            scheme: HTTP
            port: 8080
          failureThreshold: 360
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/v2.0/ping
            scheme: HTTP
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v2.0/ping
            scheme: HTTP
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: "myharbor2-core"
        - secretRef:
            name: "myharbor2-core"
        env:
          - name: CORE_SECRET
            valueFrom:
              secretKeyRef:
                name: myharbor2-core
                key: secret
          - name: JOBSERVICE_SECRET
            valueFrom:
              secretKeyRef:
                name: "myharbor2-jobservice"
                key: JOBSERVICE_SECRET
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/core/app.conf
          subPath: app.conf
        - name: secret-key
          mountPath: /etc/core/key
          subPath: key
        - name: token-service-private-key
          mountPath: /etc/core/private_key.pem
          subPath: tls.key
        - name: ca-download
          mountPath: /etc/core/ca
        - name: psc
          mountPath: /etc/core/token
      volumes:
      - name: config
        configMap:
          name: myharbor2-core
          items:
            - key: app.conf
              path: app.conf
      - name: secret-key
        secret:
          secretName: myharbor2-core
          items:
            - key: secretKey
              path: key
      - name: token-service-private-key
        secret:
          secretName: myharbor2-core
      - name: ca-download
        secret:
      - name: psc
        emptyDir: {}
