---
# Source: harbor/templates/registry/registry-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "myharbor1-registry"
  labels:
    heritage: Helm
    release: myharbor1
    chart: harbor
    app: "harbor"
type: Opaque
data:
  REGISTRY_HTTP_SECRET: "UkFRVWw5WEJCVzZNanJ1Yg=="
  REGISTRY_REDIS_PASSWORD: ""
---
# Source: harbor/templates/registry/registry-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "myharbor1-registry-htpasswd"
  labels:
    heritage: Helm
    release: myharbor1
    chart: harbor
    app: "harbor"
type: Opaque
data:
  REGISTRY_HTPASSWD: "aGFyYm9yX3JlZ2lzdHJ5X3VzZXI6JDJhJDEwJEtXd1FDaWltODlHYlExT0VBd2VrUXV4Z29td0ZQM0Z0dWZFd3h1cC5mTlhNekxNWG1wTXRt"
