---
# Source: harbor/templates/trivy/trivy-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: "myharbor2-trivy"
  labels:
    heritage: Helm
    release: myharbor2
    chart: harbor
    app: "harbor"
spec:
  ports:
    - name: http-trivy
      protocol: TCP
      port: 8080
  selector:
    release: myharbor2
    app: "harbor"
    component: trivy
