---
# Source: harbor/templates/redis/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myharbor2-redis
  labels:
    heritage: Helm
    release: myharbor2
    chart: harbor
    app: "harbor"
    component: redis
spec:
  replicas: 1
  serviceName: myharbor2-redis
  selector:
    matchLabels:
      release: myharbor2
      app: "harbor"
      component: redis
  template:
    metadata:
      labels:
        heritage: Helm
        release: myharbor2
        chart: harbor
        app: "harbor"
        component: redis
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 120
      containers:
      - name: redis
        image: goharbor/redis-photon:v2.9.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 1
          periodSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /var/lib/redis
          subPath: 
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        heritage: Helm
        release: myharbor2
        chart: harbor
        app: "harbor"
      annotations:
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "mylocalsc1"
      resources:
        requests:
          storage: "1Gi"
