---
# Source: harbor/templates/jobservice/jobservice-dpl.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "myharbor2-jobservice"
  labels:
    heritage: Helm
    release: myharbor2
    chart: harbor
    app: "harbor"
    component: jobservice
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      release: myharbor2
      app: "harbor"
      component: jobservice
  template:
    metadata:
      labels:
        heritage: Helm
        release: myharbor2
        chart: harbor
        app: "harbor"
        component: jobservice
      annotations:
        checksum/configmap: 7c5e8506c3f7076d2ba4a62396d224247a214cdcb852843b0fbc7ebc555e2be2
        checksum/configmap-env: 70b5d793729fdf71ad4e7b1aca685c3623c1a5e35568707f5713d7cef034fc7b
        checksum/secret: 81918d0650acc587772828f12869a4ea81e18f14e196dcd61e5c776b03b35034
        checksum/secret-core: f6497062bfb0ca07397f54a8e878ea98123bea377cbbf0d379ac118d913af033
    spec:
      securityContext:
        runAsUser: 10000
        fsGroup: 10000
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 120
      containers:
      - name: jobservice
        image: goharbor/harbor-jobservice:v2.9.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /api/v1/stats
            scheme: HTTP
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/stats
            scheme: HTTP
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        env:
          - name: CORE_SECRET
            valueFrom:
              secretKeyRef:
                name: myharbor2-core
                key: secret
        envFrom:
        - configMapRef:
            name: "myharbor2-jobservice-env"
        - secretRef:
            name: "myharbor2-jobservice"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jobservice-config
          mountPath: /etc/jobservice/config.yml
          subPath: config.yml
        - name: job-logs
          mountPath: /var/log/jobs
          subPath: 
      volumes:
      - name: jobservice-config
        configMap:
          name: "myharbor2-jobservice"
      - name: job-logs
        persistentVolumeClaim:
          claimName: myharbor2-jobservice
