---
# Source: harbor/templates/jobservice/jobservice-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "myharbor2-jobservice"
  labels:
    heritage: Helm
    release: myharbor2
    chart: harbor
    app: "harbor"
type: Opaque
data:
  JOBSERVICE_SECRET: "d0JvdzAzZ0p5UHZYa0xteQ=="
  REGISTRY_CREDENTIAL_PASSWORD: "aGFyYm9yX3JlZ2lzdHJ5X3Bhc3N3b3Jk"
