---
# Source: harbor/templates/jobservice/jobservice-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: "myharbor2-jobservice"
  labels:
    heritage: Helm
    release: myharbor2
    chart: harbor
    app: "harbor"
spec:
  ports:
    - name: http-jobservice
      port: 80
      targetPort: 8080
  selector:
    release: myharbor2
    app: "harbor"
    component: jobservice
